import { Product } from '../types/product';

export function getPokeData(): Product[] {
  return [
    {
      id: 1,
      name: 'Bulbasaur',
      icon: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/1.png',
      price: 12.5,
      availability: 60,
    },
    {
      id: 2,
      name: 'Ivysaur',
      icon: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/2.png',
      price: 25.0,
      availability: 30,
    },
    {
      id: 3,
      name: 'Venusaur',
      icon: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/3.png',
      price: 50.0,
      availability: 15,
    },
    {
      id: 4,
      name: 'Charmander',
      icon: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/4.png',
      price: 15.0,
      availability: 70,
    },
    {
      id: 5,
      name: 'Charmeleon',
      icon: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/5.png',
      price: 30.0,
      availability: 35,
    },
    {
      id: 6,
      name: 'Charizard',
      icon: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/6.png',
      price: 60.0,
      availability: 18,
    },
    {
      id: 7,
      name: 'Squirtle',
      icon: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/7.png',
      price: 13.0,
      availability: 65,
    },
    {
      id: 8,
      name: 'Wartortle',
      icon: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/8.png',
      price: 26.0,
      availability: 32,
    },
    {
      id: 9,
      name: 'Blastoise',
      icon: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/9.png',
      price: 52.0,
      availability: 16,
    },
    {
      id: 10,
      name: 'Caterpie',
      icon: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/10.png',
      price: 5.0,
      availability: 100,
    },
    {
      id: 11,
      name: 'Metapod',
      icon: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/11.png',
      price: 7.5,
      availability: 80,
    },
    {
      id: 12,
      name: 'Butterfree',
      icon: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/12.png',
      price: 15.0,
      availability: 40,
    },
    {
      id: 13,
      name: 'Weedle',
      icon: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/13.png',
      price: 4.5,
      availability: 110,
    },
    {
      id: 14,
      name: 'Kakuna',
      icon: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/14.png',
      price: 7.0,
      availability: 90,
    },
    {
      id: 15,
      name: 'Beedrill',
      icon: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/15.png',
      price: 14.0,
      availability: 45,
    },
    {
      id: 16,
      name: 'Pidgey',
      icon: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/16.png',
      price: 6.0,
      availability: 120,
    },
    {
      id: 17,
      name: 'Pidgeotto',
      icon: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/17.png',
      price: 12.0,
      availability: 60,
    },
    {
      id: 18,
      name: 'Pidgeot',
      icon: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/18.png',
      price: 24.0,
      availability: 30,
    },
    {
      id: 19,
      name: 'Rattata',
      icon: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/19.png',
      price: 3.0,
      availability: 150,
    },
    {
      id: 20,
      name: 'Raticate',
      icon: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/20.png',
      price: 9.0,
      availability: 75,
    },
    {
      id: 21,
      name: 'Spearow',
      icon: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/21.png',
      price: 5.5,
      availability: 115,
    },
    {
      id: 22,
      name: 'Fearow',
      icon: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/22.png',
      price: 11.0,
      availability: 57,
    },
    {
      id: 23,
      name: 'Ekans',
      icon: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/23.png',
      price: 8.0,
      availability: 85,
    },
    {
      id: 24,
      name: 'Arbok',
      icon: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/24.png',
      price: 16.0,
      availability: 42,
    },
    {
      id: 25,
      name: 'Pikachu',
      icon: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/25.png',
      price: 20.0,
      availability: 50,
    },
    {
      id: 26,
      name: 'Raichu',
      icon: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/26.png',
      price: 40.0,
      availability: 25,
    },
    {
      id: 27,
      name: 'Sandshrew',
      icon: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/27.png',
      price: 7.0,
      availability: 95,
    },
    {
      id: 28,
      name: 'Sandslash',
      icon: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/28.png',
      price: 14.0,
      availability: 47,
    },
    {
      id: 29,
      name: 'Nidoran♀',
      icon: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/29.png',
      price: 9.0,
      availability: 80,
    },
    {
      id: 30,
      name: 'Nidorina',
      icon: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/30.png',
      price: 18.0,
      availability: 40,
    },
    {
      id: 31,
      name: 'Nidoqueen',
      icon: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/31.png',
      price: 36.0,
      availability: 20,
    },
    {
      id: 32,
      name: 'Nidoran♂',
      icon: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/32.png',
      price: 9.5,
      availability: 75,
    },
    {
      id: 33,
      name: 'Nidorino',
      icon: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/33.png',
      price: 19.0,
      availability: 37,
    },
    {
      id: 34,
      name: 'Nidoking',
      icon: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/34.png',
      price: 38.0,
      availability: 18,
    },
    {
      id: 35,
      name: 'Clefairy',
      icon: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/35.png',
      price: 11.0,
      availability: 68,
    },
    {
      id: 36,
      name: 'Clefable',
      icon: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/36.png',
      price: 22.0,
      availability: 34,
    },
    {
      id: 37,
      name: 'Vulpix',
      icon: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/37.png',
      price: 14.0,
      availability: 72,
    },
    {
      id: 38,
      name: 'Ninetales',
      icon: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/38.png',
      price: 28.0,
      availability: 36,
    },
    {
      id: 39,
      name: 'Jigglypuff',
      icon: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/39.png',
      price: 10.0,
      availability: 88,
    },
    {
      id: 40,
      name: 'Wigglytuff',
      icon: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/40.png',
      price: 20.0,
      availability: 44,
    },
    {
      id: 41,
      name: 'Zubat',
      icon: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/41.png',
      price: 4.0,
      availability: 130,
    },
    {
      id: 42,
      name: 'Golbat',
      icon: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/42.png',
      price: 12.0,
      availability: 65,
    },
    {
      id: 43,
      name: 'Oddish',
      icon: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/43.png',
      price: 8.5,
      availability: 92,
    },
    {
      id: 44,
      name: 'Gloom',
      icon: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/44.png',
      price: 17.0,
      availability: 46,
    },
    {
      id: 45,
      name: 'Vileplume',
      icon: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/45.png',
      price: 34.0,
      availability: 23,
    },
    {
      id: 46,
      name: 'Paras',
      icon: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/46.png',
      price: 6.5,
      availability: 105,
    },
    {
      id: 47,
      name: 'Parasect',
      icon: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/47.png',
      price: 13.0,
      availability: 52,
    },
    {
      id: 48,
      name: 'Venonat',
      icon: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/48.png',
      price: 7.5,
      availability: 100,
    },
    {
      id: 49,
      name: 'Venomoth',
      icon: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/49.png',
      price: 15.0,
      availability: 50,
    },
    {
      id: 50,
      name: 'Diglett',
      icon: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/50.png',
      price: 5.0,
      availability: 125,
    },
    {
      id: 51,
      name: 'Dugtrio',
      icon: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/51.png',
      price: 15.0,
      availability: 62,
    },
    {
      id: 52,
      name: 'Meowth',
      icon: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/52.png',
      price: 18.0,
      availability: 55,
    },
    {
      id: 53,
      name: 'Persian',
      icon: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/53.png',
      price: 36.0,
      availability: 27,
    },
    {
      id: 54,
      name: 'Psyduck',
      icon: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/54.png',
      price: 12.0,
      availability: 78,
    },
    {
      id: 55,
      name: 'Golduck',
      icon: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/55.png',
      price: 24.0,
      availability: 40,
    },
    {
      id: 56,
      name: 'Mankey',
      icon: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/56.png',
      price: 9.0,
      availability: 90,
    },
    {
      id: 57,
      name: 'Primeape',
      icon: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/57.png',
      price: 18.0,
      availability: 45,
    },
    {
      id: 58,
      name: 'Growlithe',
      icon: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/58.png',
      price: 16.0,
      availability: 66,
    },
    {
      id: 59,
      name: 'Arcanine',
      icon: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/59.png',
      price: 32.0,
      availability: 33,
    },
    {
      id: 60,
      name: 'Poliwag',
      icon: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/60.png',
      price: 7.0,
      availability: 102,
    },
    {
      id: 61,
      name: 'Poliwhirl',
      icon: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/61.png',
      price: 14.0,
      availability: 51,
    },
    {
      id: 62,
      name: 'Poliwrath',
      icon: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/62.png',
      price: 28.0,
      availability: 25,
    },
    {
      id: 63,
      name: 'Abra',
      icon: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/63.png',
      price: 13.0,
      availability: 70,
    },
    {
      id: 64,
      name: 'Kadabra',
      icon: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/64.png',
      price: 26.0,
      availability: 35,
    },
    {
      id: 65,
      name: 'Alakazam',
      icon: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/65.png',
      price: 52.0,
      availability: 17,
    },
    {
      id: 66,
      name: 'Machop',
      icon: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/66.png',
      price: 8.0,
      availability: 98,
    },
    {
      id: 67,
      name: 'Machoke',
      icon: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/67.png',
      price: 16.0,
      availability: 49,
    },
    {
      id: 68,
      name: 'Machamp',
      icon: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/68.png',
      price: 32.0,
      availability: 24,
    },
    {
      id: 69,
      name: 'Bellsprout',
      icon: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/69.png',
      price: 6.0,
      availability: 110,
    },
    {
      id: 70,
      name: 'Weepinbell',
      icon: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/70.png',
      price: 12.0,
      availability: 55,
    },
    {
      id: 71,
      name: 'Victreebel',
      icon: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/71.png',
      price: 24.0,
      availability: 27,
    },
    {
      id: 72,
      name: 'Tentacool',
      icon: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/72.png',
      price: 5.5,
      availability: 118,
    },
    {
      id: 73,
      name: 'Tentacruel',
      icon: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/73.png',
      price: 11.0,
      availability: 59,
    },
    {
      id: 74,
      name: 'Geodude',
      icon: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/74.png',
      price: 7.0,
      availability: 108,
    },
    {
      id: 75,
      name: 'Graveler',
      icon: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/75.png',
      price: 14.0,
      availability: 54,
    },
    {
      id: 76,
      name: 'Golem',
      icon: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/76.png',
      price: 28.0,
      availability: 26,
    },
    {
      id: 77,
      name: 'Ponyta',
      icon: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/77.png',
      price: 15.0,
      availability: 64,
    },
    {
      id: 78,
      name: 'Rapidash',
      icon: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/78.png',
      price: 30.0,
      availability: 32,
    },
    {
      id: 79,
      name: 'Slowpoke',
      icon: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/79.png',
      price: 10.0,
      availability: 85,
    },
    {
      id: 80,
      name: 'Slowbro',
      icon: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/80.png',
      price: 20.0,
      availability: 42,
    },
    {
      id: 81,
      name: 'Magnemite',
      icon: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/81.png',
      price: 11.0,
      availability: 75,
    },
    {
      id: 82,
      name: 'Magneton',
      icon: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/82.png',
      price: 22.0,
      availability: 37,
    },
    {
      id: 83,
      name: "Farfetch'd",
      icon: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/83.png',
      price: 22.0,
      availability: 48,
    },
    {
      id: 84,
      name: 'Doduo',
      icon: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/84.png',
      price: 9.0,
      availability: 95,
    },
    {
      id: 85,
      name: 'Dodrio',
      icon: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/85.png',
      price: 18.0,
      availability: 47,
    },
    {
      id: 86,
      name: 'Seel',
      icon: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/86.png',
      price: 8.0,
      availability: 100,
    },
    {
      id: 87,
      name: 'Dewgong',
      icon: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/87.png',
      price: 16.0,
      availability: 50,
    },
    {
      id: 88,
      name: 'Grimer',
      icon: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/88.png',
      price: 6.5,
      availability: 112,
    },
    {
      id: 89,
      name: 'Muk',
      icon: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/89.png',
      price: 13.0,
      availability: 56,
    },
    {
      id: 90,
      name: 'Shellder',
      icon: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/90.png',
      price: 7.5,
      availability: 105,
    },
    {
      id: 91,
      name: 'Cloyster',
      icon: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/91.png',
      price: 15.0,
      availability: 52,
    },
    {
      id: 92,
      name: 'Gastly',
      icon: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/92.png',
      price: 14.0,
      availability: 70,
    },
    {
      id: 93,
      name: 'Haunter',
      icon: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/93.png',
      price: 28.0,
      availability: 35,
    },
    {
      id: 94,
      name: 'Gengar',
      icon: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/94.png',
      price: 56.0,
      availability: 17,
    },
    {
      id: 95,
      name: 'Onix',
      icon: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/95.png',
      price: 25.0,
      availability: 40,
    },
    {
      id: 96,
      name: 'Drowzee',
      icon: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/96.png',
      price: 10.0,
      availability: 90,
    },
    {
      id: 97,
      name: 'Hypno',
      icon: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/97.png',
      price: 20.0,
      availability: 45,
    },
    {
      id: 98,
      name: 'Krabby',
      icon: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/98.png',
      price: 8.5,
      availability: 97,
    },
    {
      id: 99,
      name: 'Kingler',
      icon: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/99.png',
      price: 17.0,
      availability: 48,
    },
    {
      id: 100,
      name: 'Voltorb',
      icon: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/100.png',
      price: 9.0,
      availability: 85,
    },
  ];
}
